+---------------------------------------------------------------------------------------------------+
|                                          Project Overview                                         |
+---------------------------------------------------------------------------------------------------+
| This project reads lines from a file, handling dynamic memory, buffering, and efficient line      |
| extraction. It works by reading chunks of data into a buffer, then extracting each line when a    |
| newline character is encountered.                                                                 |
+---------------------------------------------------------------------------------------------------+


+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|         Component               |                                                      Description                                                                                                               |                                             Why it Works                                                                                                                 |
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Header File (`get_next_line.h`) | Defines necessary includes, function prototypes, and the `BUFFER_SIZE` constant.                                                                                             | Modularization: Functions are clearly declared and separated, ensuring easy maintainability and clarity.                                                                 |
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `get_next_line(int fd)`         | Main function: Reads the next line from the file descriptor. Uses the buffer for line extraction.                                                                             | Buffering & Line Extraction: Handles reading from a file and extracting a full line, using helper functions for buffer management.                                      |
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `ft_memcpy(void *dest, const void *src, size_t n)` | Copies `n` bytes of data from `src` to `dest`.                                                                                                            | Efficient Memory Copying: Safely copies memory, used to handle buffer data transfers and string manipulations.                                                           |
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `ft_strlen_until(const char *s, int c)` | Returns the length of a string up to a specified character `c`.                                                                                             | Line/Buffer Length Calculation: Helps determine where a line ends or the length of content before a newline, guiding the extraction process.                            |
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `ft_strdup_len(const char *s, size_t len)`   | Creates a duplicate of a substring up to `len` characters.                                                                                                           | Precise Memory Allocation: Only the required portion of the string is duplicated, optimizing memory usage.                                                             |
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `ft_strchr(const char *s, int c)`      | Finds the first occurrence of a character in the string.                                                                                             | Character Search: Used to locate newline characters, marking the end of a line or data block.                                                                   |
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `ft_strjoin_and_free(char *s1, const char *s2)` | Concatenates two strings into a new string, freeing the first string (`s1`).                                                                                           | Efficient String Handling: Joins strings and prevents memory leaks by freeing the original string (`s1`).                                                           |
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `ft_read_to_buffer(int fd, char *buffer)`  | Reads from the file descriptor into the buffer until a newline or EOF is found.                                                                                      | Data Acquisition: Ensures that data is read from the file in manageable chunks and appended to the buffer for processing.                                           |
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `ft_extract_line(char **buffer)` | Extracts a line from the buffer, reallocating space for the remaining content after the line is extracted.                                                                | Line Parsing: Handles extracting lines from the buffer and updating the buffer with remaining content.                                                             |
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Memory Management              | Memory is allocated dynamically for each string or buffer and freed appropriately after use.                                                                                | No Memory Leaks: Functions like `ft_strdup_len()` and `ft_strjoin_and_free()` handle dynamic memory and prevent memory leaks.                                          |
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Buffer Handling                | The buffer grows dynamically as data is read, with lines being extracted and the remaining buffer reused.                                                                  | Efficient Buffering: Allows reading from a file without reloading data unnecessarily, keeping only what's needed for the next line.                                    |
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+


Note to self:
Compilation:
To compile your test program, use the same command:

gcc -o gnl_test test.c get_next_line.c -D BUFFER_SIZE=42
Running the Tests:
Once compiled, you can run the gnl_test executable:

./gnl_test
This will execute all your test cases and print the results for each one.